---
title: "Reverse_engineering2"
author: "Akira Kyles"
date: "2025-10-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(lubridate)
library(janitor)
```

```{r}
deaths <- read_csv("C:/Users/AKBas/Documents/GitHub/jour772/data-police-shootings/v2/fatal-police-shootings-data.csv")
```
```{r}
deaths_agencies <- read_csv("C:/Users/AKBas/Documents/GitHub/jour772/data-police-shootings/v2/fatal-police-shootings-agencies.csv")
```
###Akira Kyles
```{r}
#By race, 147 of the women killed were White, 48 Black and 29 Hispanic. Five were Native American, four were Asian and three were other races.
deaths |> 
  filter(date < "2020-09-01" &
           gender== "female") |> 
  group_by(race) |> 
  summarise(count=n()) 
  
```
```{r}
###By percentages, men shot by police were less often White and more often Black or Hispanic. 
###My data shows this statement as false and it was actually the complete opposite. 
deaths |> 
  filter(date < "2020-09-03" &
           gender== "male" & 
           armed_with== "gun" & 
           threat_type== "shoot") |> 
  group_by(race) |> 
  summarise(count = n()) |> 
  mutate(percentage = (count / sum(count)) * 100)
 
```